dev: cuda
out_dir: outputs/example_energy_prediction
out_name: example_energy_prediction
input_list: inputs/example_list_energy_prediction.txt
input_dir: inputs/example_pdbs
mutant_fasta: null
mutant_csv: null
model:
  check_path: vanilla_model_weights/pottsmpnn_20.pt
  hidden_dim: 128
  edge_features: 128
  potts_dim: 400
  num_layers: 3
  num_edges: 48
  vocab: 21
inference:
  ddG: true
  mean_norm: false
  max_tokens: 20000
  filter: false
  binding_energy_json: null
  binding_energy_cutoff: 8
  skip_gaps: false
  noise: 0.0
  chain_dict: null
  chain_ranges: inputs/example_chain_ranges.json
